version: '3.2'

services:

  apache:
    container_name: apache
    build: ./apache
    ports:
     - "8080:80"
    volumes:
      - web:/var/www/html

  mysql:
    container_name: mys
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bEq!QgZ
    volumes:
      - db:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - web:/var/www/html

volumes:
  db:
  web:

